config/routes.rb
Rails.application.routes.draw do

  root "site/home#index"

  get "dashboard", to: "backoffice/dashboard#index"
  namespace :backoffice do
    #get 'admins', to: "admins#index"
    resources :admins, except: [:show]
    resources :categories, except: [:show, :destroy]
    resources :send_messages, only: [:edit, :create]
    resources :diagrams, only: [:index]
  end

  namespace :site do
    get "home", to: "home#index"

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_detail, only: [:show, :index]
    resources :category, only: [:show]
    resources :comments, only: [:create]

    get "search", to: "search#ads"
  end

  devise_for :admins, :skip => :registration
  devise_for :members,
   controllers: {
     sessions: "members/sessions",
     registrations: "members/registrations"
  }

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController

  before_action :set_admin, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: [:new, :destroy]
  after_action :verify_policy_scoped, only: :index

  def index
    #@admins = Admin.all
    #@admins = Admin.with_restricted_access
    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      redirect_to backoffice_admins_path, notice: I18n.t('messages.created_with', item: @admin.name)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @admin.update(admin_params)
      AdminMailer.update_mailer(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: I18n.t('messages.updated_with', item: @admin.name)
    else
      render :edit
    end
  end

  def destroy
    authorize  @admin
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: I18n.t('messages.destroyed_with', item: @admin.name)
    else
      render :index
    end
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def admin_params

    if password_blank?
      params[:admin].extract!(:password, :password_confirmation)
    end

    if @admin.blank?
      params.require(:admin).permit(:email, :name, :role, :password, :password_confirmation)
    else
      params.require(:admin).permit(policy(@admin).permitted_attributes)
    end

  end

  def password_blank?
    params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
  end

end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]

  def index
    @categories = Category.all.order(:asc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = CategoryService.create(category_params)

    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: "Categoria #{@category.description} cadastrada!"
    else
      render :new
    end

    # @category = Category.new(category_params)
    # if @category.save
    #   redirect_to backoffice_categories_path, notice: "Categoria #{@category.description} cadastrada!"
    # else
    #   render :new
    # end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to backoffice_categories_path, notice: "Categoria #{@category.description} atualizada!"
    else
      render :edit
    end
  end

  private

  def category_params
    params.require(:category).permit(:description)
  end

  def set_category
    @category = Category.friendly.find(params[:id])
  end

end

app/controllers/backoffice/categories_controller/category_service.rb
class  Backoffice::CategoriesController::CategoryService

  attr_accessor :category

  def self.create(params_category)
    @category = Category.new(params_category)
    @category.save! if @category.valid?
    @category
  end
end

app/controllers/backoffice/dashboard_controller.rb
#rails g controller backoffice/dashboard index

class Backoffice::DashboardController < BackofficeController

  def index
  end
end

app/controllers/backoffice/diagrams_controller.rb
class Backoffice::DiagramsController < BackofficeController
  def index
    %x(bundle exec erd --filename='public/diagram')
  end
end

app/controllers/backoffice/send_messages_controller.rb
class Backoffice::SendMessagesController < ApplicationController

  def edit
    @admin = Admin.find(params[:id])
  end

  def create
    begin
      AdminMailer.send_message(current_admin,
                               params[:recipient],
                               params[:subject],
                               params[:message]).deliver_now

      @notify_message = I18n.t('messages.email_delivered')
      @notify_flag = "success"
    rescue
      @notify_message = I18n.t('messages.email_not_delivered')
      @notify_flag = "error"
    end

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController

  before_action :authenticate_admin!

  layout "backoffice"

  def pundit_user
    current_admin
  end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper

  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    # options = []
    # Admin.roles_i18n.each do |key, value|
    #   options.push(OptionsForRoles.new(key, value))
    # end
    # options

    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end

  end
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/diagrams_helper.rb
module Backoffice::DiagramsHelper
end

app/helpers/backoffice/send_messagess_helper.rb
module Backoffice::SendMessagessHelper
end

app/views/backoffice/admins/edit.html.erb
<%= render partial: "/backoffice/admins/shared/form",
           locals: { action: "Editando Administrador" }
%>

app/views/backoffice/admins/index.html.erb
<div class="card shadow mb-4">

   <div class="card-header py-3">
     <h6 class="m-0 font-weight-bold text-primary">
      <%= t("messages.listing", model: @admins.model_name.human(count: @admins.count)) %>
      <% if policy(@admins).new? %>
        <%= link_to new_backoffice_admin_path, class: "btn btn-success btn-circle float-right" do %>
          <i class="fas fa-plus"></i>
        <% end %>
      <% else %>
        <span class="btn btn-success btn-circle disabled float-right">
            <i class="fas fa-plus"></i>
        </span>
      <% end %>
     </h6>
   </div>

   <div class="card-body">
      <div class="table-responsive">
         <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">

            <div class="row">
               <div class="col-sm-12">
                  <table class="table table-bordered dataTable" id="dataTable"
                         width="100%" cellspacing="0" role="grid"
                         aria-describedby="dataTable_info" style="width: 100%;">
                    <thead>
                      <tr role="row">
                        <th  class="sorting_asc" tabindex="0" aria-controls="dataTable"
                             rowspan="1" colspan="1" aria-sort="ascending"
                             aria-label="Name: activate to sort column descending"
                             style="width: 141px;">
                          <%= @admins.model.human_attribute_name("name") %>
                        </th>
                        <th  class="sorting_asc" tabindex="0" aria-controls="dataTable"
                             rowspan="1" colspan="1" aria-sort="ascending"
                             aria-label="Name: activate to sort column descending"
                             style="width: 141px;">
                          <%= @admins.model.human_attribute_name("email") %>
                        </th>

                        <th  class="sorting_asc" tabindex="0" aria-controls="dataTable"
                             rowspan="1" colspan="1" aria-sort="ascending"
                             aria-label="Name: activate to sort column descending"
                             style="width: 141px;">
                          <%= @admins.model.human_attribute_name("role") %>
                        </th>

                        <th  class="sorting" tabindex="0" aria-controls="dataTable"
                             rowspan="1" colspan="1"
                             aria-label="Position: activate to sort column ascending"
                             style="width: 100px; text-align: center;">
                        </th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @admins.each do |admin| %>
                        <tr role="row" class="odd">

                          <td class="sorting_1"><%= admin.name %></td>

                          <td class="sorting_1"> <%= admin.email %> </td>

                          <td class="sorting_1"><%= admin.role_i18n %></td>

                          <td style="text-align: center;">
                            <%= link_to edit_backoffice_send_message_path(admin),
                                  class: "btn btn-primary btn-circle btn-sm fooo",
                                  remote: true do %>
                                    <i class="fas fa-envelope"></i>
                            <% end %>
                            <%= link_to edit_backoffice_admin_path(admin),
                                class: "btn btn-info btn-circle btn-sm" do %>
                                <i class="fas fa-edit"></i>
                            <% end %>

                            <% if admin.id != current_admin.id && policy(admin).destroy? %>
                              <%= link_to backoffice_admin_path(admin),
                                  method: :DELETE,
                                  class: "btn btn-warning btn-circle btn-sm fooo",
                                  data: {confirm: t("messages.confirm_with", item: admin.name)} do %>
                                    <i class="fas fa-times"></i>
                              <% end %>
                            <% else %>
                              <span class = "btn btn-warning btn-circle btn-sm  disabled">
                                  <i class="fas fa-times"></i>
                              </span>
                            <% end %>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

<%= render partial: "backoffice/admins/shared/send_message_modal" %>

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form",
           locals: { action: "Novo administrador" }
%>