config/routes.rb
Rails.application.routes.draw do

  root "site/home#index"

  get "dashboard", to: "backoffice/dashboard#index"
  namespace :backoffice do
    #get 'admins', to: "admins#index"
    resources :admins, except: [:show]
    resources :categories, except: [:show, :destroy]
    resources :send_messages, only: [:edit, :create]
    resources :diagrams, only: [:index]
  end

  namespace :site do
    get "home", to: "home#index"

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_detail, only: [:show, :index]
    resources :category, only: [:show]
    resources :comments, only: [:create]

    get "search", to: "search#ads"
  end

  devise_for :admins, :skip => :registration
  devise_for :members,
   controllers: {
     sessions: "members/sessions",
     registrations: "members/registrations"
  }

end

app/models/ad.rb
class Ad < ApplicationRecord

  extend FriendlyId

  PER_PAGE = 6

  friendly_id :title, use: :slugged

  before_save :md_to_hml

  belongs_to :category, counter_cache: true
  belongs_to :member

  has_many :comments

  validates_presence_of  :picture

  validates :title, :description_md, :description_short, :category, presence: true
  validates :picture, :finish_date, presence: true
  validates :price, numericality: { greater_than: 0 }

  monetize :price_cents

  scope :descending_order, ->(page) {
     order(created_at: :desc).page(page).per(PER_PAGE)
  }

  scope :by_search, ->(term, page) {
     where("lower(title) LIKE ?", "%#{term.downcase}%").page(page).per(PER_PAGE)
  }

  scope :by_category, ->(id, page) {
   where(category: id).page(page).per(PER_PAGE)
 }

  scope :to_the, ->(member) { where(member: member) }

  scope :carousel, ->(quantity) { limit(quantity).order("RANDOM()") }

  #rake paperclip:refresh  CLASS=Ad
  has_attached_file :picture,
                     styles: { medium: "320x150#", thumb: "100x100>", large: "900X350#" },
                     default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  def second
    self[1]
  end

  def third
    self[2]
  end

  private
    def md_to_hml
      options = {
          filter_html: true,
          link_attributes: {
            rel: "nofollow",
            target: "_blank"
          }
      }

      extensions = {
        space_after_headers: true,
        autolink: true
      }

      renderer = Redcarpet::Render::HTML.new(options)
      markdown = Redcarpet::Markdown.new(renderer, extensions)
      self.description = markdown.render(self.description_md)
    end
end

app/models/admin.rb
class Admin < ApplicationRecord

  validates_presence_of :name
=begin Trabalhando com Enuns 1
  enum role: { :full_access, :restricted_access }
  enum role: [ :full_access => 0, :restricted_access => 1]
  scope :with_full_access, -> { where(role: :full_access).order(:asc) }
=end

  # Trabalhando com Enuns 2
  #Constant with block
  ROLES = { :full_access => 0, :restricted_access => 1 }

  enum role: ROLES

  scope :with_full_access, -> { where(role: ROLES[:full_access ]).order(:asc) }
  scope :with_restricted_access, -> { where(role: ROLES[:restricted_access]).order(:asc) }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  extend FriendlyId
  friendly_id :description, use: :slugged

  validates_presence_of :description

  has_many :ads

  scope :linked_ad_order_by_description, -> { joins(:ads).distinct.order(:description) }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :ad
end

app/models/member.rb
class Member < ApplicationRecord

  has_many :ads
  has_one :profile_member

  accepts_nested_attributes_for :profile_member

  validate :nested_attributes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  MUST_BE_VALID_NESTED_ATTRIBUTES = { 1 => "first_name", 2 => "second_name" }

  def nested_attributes
    profile_member.attributes.each do |attribute, value|
      if MUST_BE_VALID_NESTED_ATTRIBUTES.has_value?(attribute) and value.blank?
        add_error_nested_attributes(attribute)
      end
    end
  end

  def add_error_nested_attributes(attribute)
    errors.add(:base, "#{ProfileMember.human_attribute_name(attribute)} deve ser preenchido")
  end

end

app/models/profile_member.rb
class ProfileMember < ApplicationRecord
  belongs_to :member

  def full_name
    "#{self.first_name} #{self.second_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :store_user_location!, unless: :devise_controller?
  #before_action :store_user_location!, if: :storable_location?

  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  layout :layout_by_resource

  protected
    def layout_by_resource
      if devise_controller? && resource_name == :admin
        "backoffice_devise"
      elsif devise_controller? && resource_name == :member
        "site_devise"
      else
        "application"
      end
    end

    def user_not_authorized
      flash[:alert] = "Você não tem permissão."
      redirect_to request.referrer || root_path
    end

  private
    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
    end

    def store_user_location!
      store_location_for(:member, request.fullpath)
    end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController

  before_action :authenticate_admin!

  layout "backoffice"

  def pundit_user
    current_admin
  end
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController

  def index
    @categories = Category.linked_ad_order_by_description
    @ads = Ad.descending_order(params[:page])
    @ad_carousels = Ad.carousel(3)
  end

end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController

  def ads
    @categories = Category.linked_ad_order_by_description
    @ads = Ad.by_search(params[:q], params[:page])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "site"
end

app/helpers/application_helper.rb
module ApplicationHelper

  def devise_sign_in?
    params[:controller] == "members/sessions" ? "" : "display:none;"
  end

  def devise_sign_up?
    params[:controller] == "members/registrations" ? "" : "display:none;"
  end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper

  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    # options = []
    # Admin.roles_i18n.each do |key, value|
    #   options.push(OptionsForRoles.new(key, value))
    # end
    # options

    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end

  end
end

app/helpers/backoffice/diagrams_helper.rb
module Backoffice::DiagramsHelper
end

app/helpers/site/ad_detail_helper.rb
module Site::AdDetailHelper
end

app/helpers/site/category_helper.rb
module Site::CategoryHelper
end

app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/backoffice/admins/shared/_form.html.erb
<div class="card shadow mb-4">
   <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary"><%= "#{action}" %></h6>
   </div>

   <div class="card-body">
      <%= render partial: "shared/messages", locals: { record: @admin } %>

      <%= form_with(model: [:backoffice, @admin], local: true ) do |f| %>

        <div class="form-group">
          <%= f.label "Nome" %>
          <%= f.text_field :name, class: "form-control col-md-4" %>
        </div>

        <div class="form-group">
          <%= f.label "E-mail" %>
          <%= f.text_field :email, class: "form-control col-md-4" %>
        </div>

        <% if policy(@admin).edit? %>
          <div class="form-group">
            <%= f.label :role %>
            <%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
              <div class="form-check">
                <%=  b.label(class: "form-check-label") { b.radio_button(class: "form-check-input") + b.text } %>
              </div>
            <% end %>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label "Senha" %>
          <%= f.text_field :password, class: "form-control col-md-4"%>
        </div>

        <div class="form-group">
          <%= f.label "Confirmação" %>
          <%= f.text_field :password_confirmations, class: "form-control col-md-4" %>
        </div>

        <%= f.submit "Salvar", class: "btn btn-success" %>
      <% end %>
   </div>
</div>

app/views/backoffice/admins/shared/_send_message_modal.html.erb
<div class="modal fade" id="sendMessageModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="messageModalLabel">Message Head</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= form_with url: backoffice_send_messages_path do |form| %>

          <div class="form-group">
            <%= form.label "Destinatário", class: "col-form-label" %>
            <%= form.text_field :recipient, class: "form-control", id: "recipient-name", readonly: "readonly" %>
          </div>

          <div class="form-group">
            <%= form.label "Assunto", class: "col-form-label" %>
            <%= form.text_field :subject, class: "form-control", id: "subject-text" %>
          </div>

          <div class="form-group">
            <%= form.label "Mensagem", class: "col-form-label" %>
            <%= form.text_area :message, class: "form-control", id: "message-text" %>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <%= form.submit "Enviar", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_notification.html.erb
<% if flash %>
    <% flash.each do |key, value| %>
      <%= javascript_tag "$.notify(
           {
              message: '#{value}'
           },
           {
              type: '#{key == 'notice' ? 'success' : 'danger'}',
              placement:{
                from: 'top',
                align: 'center'
              }
            }
        );"
      %>
    <% end %>
<% end %>

app/views/shared/_messages.html.erb
<% if record.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <ul>
       <% record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
       <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>