config/routes.rb
Rails.application.routes.draw do

  root "site/home#index"

  get "dashboard", to: "backoffice/dashboard#index"
  namespace :backoffice do
    #get 'admins', to: "admins#index"
    resources :admins, except: [:show]
    resources :categories, except: [:show, :destroy]
    resources :send_messages, only: [:edit, :create]
    resources :diagrams, only: [:index]
  end

  namespace :site do
    get "home", to: "home#index"

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_detail, only: [:show, :index]
    resources :category, only: [:show]
    resources :comments, only: [:create]

    get "search", to: "search#ads"
  end

  devise_for :admins, :skip => :registration
  devise_for :members,
   controllers: {
     sessions: "members/sessions",
     registrations: "members/registrations"
  }

end

app/models/ad.rb
class Ad < ApplicationRecord

  extend FriendlyId

  PER_PAGE = 6

  friendly_id :title, use: :slugged

  before_save :md_to_hml

  belongs_to :category, counter_cache: true
  belongs_to :member

  has_many :comments

  validates_presence_of  :picture

  validates :title, :description_md, :description_short, :category, presence: true
  validates :picture, :finish_date, presence: true
  validates :price, numericality: { greater_than: 0 }

  monetize :price_cents

  scope :descending_order, ->(page) {
     order(created_at: :desc).page(page).per(PER_PAGE)
  }

  scope :by_search, ->(term, page) {
     where("lower(title) LIKE ?", "%#{term.downcase}%").page(page).per(PER_PAGE)
  }

  scope :by_category, ->(id, page) {
   where(category: id).page(page).per(PER_PAGE)
 }

  scope :to_the, ->(member) { where(member: member) }

  scope :carousel, ->(quantity) { limit(quantity).order("RANDOM()") }

  #rake paperclip:refresh  CLASS=Ad
  has_attached_file :picture,
                     styles: { medium: "320x150#", thumb: "100x100>", large: "900X350#" },
                     default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  def second
    self[1]
  end

  def third
    self[2]
  end

  private
    def md_to_hml
      options = {
          filter_html: true,
          link_attributes: {
            rel: "nofollow",
            target: "_blank"
          }
      }

      extensions = {
        space_after_headers: true,
        autolink: true
      }

      renderer = Redcarpet::Render::HTML.new(options)
      markdown = Redcarpet::Markdown.new(renderer, extensions)
      self.description = markdown.render(self.description_md)
    end
end

app/models/admin.rb
class Admin < ApplicationRecord

  validates_presence_of :name
=begin Trabalhando com Enuns 1
  enum role: { :full_access, :restricted_access }
  enum role: [ :full_access => 0, :restricted_access => 1]
  scope :with_full_access, -> { where(role: :full_access).order(:asc) }
=end

  # Trabalhando com Enuns 2
  #Constant with block
  ROLES = { :full_access => 0, :restricted_access => 1 }

  enum role: ROLES

  scope :with_full_access, -> { where(role: ROLES[:full_access ]).order(:asc) }
  scope :with_restricted_access, -> { where(role: ROLES[:restricted_access]).order(:asc) }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  extend FriendlyId
  friendly_id :description, use: :slugged

  validates_presence_of :description

  has_many :ads

  scope :linked_ad_order_by_description, -> { joins(:ads).distinct.order(:description) }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :ad
end

app/models/member.rb
class Member < ApplicationRecord

  has_many :ads
  has_one :profile_member

  accepts_nested_attributes_for :profile_member

  validate :nested_attributes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  MUST_BE_VALID_NESTED_ATTRIBUTES = { 1 => "first_name", 2 => "second_name" }

  def nested_attributes
    profile_member.attributes.each do |attribute, value|
      if MUST_BE_VALID_NESTED_ATTRIBUTES.has_value?(attribute) and value.blank?
        add_error_nested_attributes(attribute)
      end
    end
  end

  def add_error_nested_attributes(attribute)
    errors.add(:base, "#{ProfileMember.human_attribute_name(attribute)} deve ser preenchido")
  end

end

app/models/profile_member.rb
class ProfileMember < ApplicationRecord
  belongs_to :member

  def full_name
    "#{self.first_name} #{self.second_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :store_user_location!, unless: :devise_controller?
  #before_action :store_user_location!, if: :storable_location?

  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  layout :layout_by_resource

  protected
    def layout_by_resource
      if devise_controller? && resource_name == :admin
        "backoffice_devise"
      elsif devise_controller? && resource_name == :member
        "site_devise"
      else
        "application"
      end
    end

    def user_not_authorized
      flash[:alert] = "Você não tem permissão."
      redirect_to request.referrer || root_path
    end

  private
    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
    end

    def store_user_location!
      store_location_for(:member, request.fullpath)
    end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController

  before_action :authenticate_admin!

  layout "backoffice"

  def pundit_user
    current_admin
  end
end

app/controllers/members/registrations_controller.rb
class Members::RegistrationsController < Devise::RegistrationsController

  before_action :configure_permitted_parameters

  def new
    build_resource({})
    resource.build_profile_member
    respond_with self.resource
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up,
      keys:[
        :email, :password, :password_cofirmation,
        :profile_member_attributes => [:first_name, :second_name]
      ]
    )
  end
end

app/controllers/members/sessions_controller.rb
class Members::SessionsController < Devise::SessionsController

  def new
    super do |resource|
      resource.build_profile_member
    end
  end

  protected

    def after_sign_in_path_for(resource)

      stored_location = stored_location_for(resource)

      if stored_location.match(site_ad_detail_index_path)
        stored_location
      else
        site_profile_dashboard_index_path
      end
    end
end

app/controllers/site/home_controller.rb
class Site::HomeController < SiteController

  def index
    @categories = Category.linked_ad_order_by_description
    @ads = Ad.descending_order(params[:page])
    @ad_carousels = Ad.carousel(3)
  end

end

app/controllers/site/profile_controller.rb
class Site::ProfileController < SiteController
layout "profile"
end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController

  def ads
    @categories = Category.linked_ad_order_by_description
    @ads = Ad.by_search(params[:q], params[:page])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout "site"
end

app/helpers/application_helper.rb
module ApplicationHelper

  def devise_sign_in?
    params[:controller] == "members/sessions" ? "" : "display:none;"
  end

  def devise_sign_up?
    params[:controller] == "members/registrations" ? "" : "display:none;"
  end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper

  OptionsForRoles = Struct.new(:id, :description)

  def options_for_roles
    # options = []
    # Admin.roles_i18n.each do |key, value|
    #   options.push(OptionsForRoles.new(key, value))
    # end
    # options

    Admin.roles_i18n.map do |key, value|
      OptionsForRoles.new(key, value)
    end

  end
end

app/helpers/backoffice/diagrams_helper.rb
module Backoffice::DiagramsHelper
end

app/helpers/members/registrations_helper.rb
module Members::RegistrationsHelper
end

app/helpers/site/ad_detail_helper.rb
module Site::AdDetailHelper
end

app/helpers/site/category_helper.rb
module Site::CategoryHelper
end

app/helpers/site/comments_helper.rb
module Site::CommentsHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/views/members/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/members/shared/_form.html.erb
<div class="container">

    <div id="loginbox" style=" <%= devise_sign_in? %> margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
      <div class="panel panel-info" >

        <div class="panel-heading">
            <div class="panel-title">Login</div>
            <div style="float:right; font-size: 80%; position: relative; top:-10px">
              <%= link_to "Esqueceu a senha ?", new_password_path(resource_name) %>
            </div>
        </div>

        <div style="padding-top:30px" class="panel-body" >

          <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12">
          </div>

          <%= form_for(resource, as: resource_name, url: session_path(resource_name),
                                 html: { class: "form-horizontal", id: "loginform"}) do |f| %>

            <div style="margin-bottom: 25px" class="input-group">
                <span class="input-group-addon">
                  <i class="glyphicon glyphicon-user"></i>
                </span>
                 <%= f.email_field :email, autofocus: true, autocomplete: "email", id: "login-username", class: "form-control", placeholder: "E-mail" %>
            </div>

            <div style="margin-bottom: 25px" class="input-group">
                <span class="input-group-addon">
                  <i class="glyphicon glyphicon-lock"></i>
                </span>
                 <%= f.password_field :password, autocomplete: "current-password", id: "login-password", type: "password", class: "form-control" %>
            </div>

            <% if devise_mapping.rememberable? %>
              <div class="input-group">
                <div class="checkbox">
                  <label>
                    <%= f.check_box :remember_me %> Lembrar-me
                  </label>
                </div>
              </div>
            <% end %>

            <div style="margin-top:10px" class="form-group">
              <div class="col-sm-12 controls">
                <%= f.submit "Login", class: "btn btn-success" %>
                <a id="btn-fblogin" href="#" class="btn btn-primary">Login with Facebook</a>
              </div>
            </div>

            <div class="form-group">
              <div class="col-md-12 control">
                <div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
                  Don't have an account!
                  <a href="#" onClick="$('#loginbox').hide(); $('#signupbox').show()">
                      Sign Up Here
                  </a>
                </div>
              </div>
            </div>
          <% end %>
        </div>
       </div>
    </div>

    <div id="signupbox" style="<%= devise_sign_up? %> margin-top:50px" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
        <div class="panel panel-info">

            <div class="panel-heading">
                <div class="panel-title">Cadastrar</div>
                <div style="float:right; font-size: 85%; position: relative; top:-10px">
                  <a id="signinlink" href="#" onclick="$('#signupbox').hide(); $('#loginbox').show()">
                    Login
                  </a>
                </div>
            </div>

            <div class="panel-body" >
              <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { class: "form-horizontal" }) do |f| %>

                  <div class="form-group">
                      <%= f.label :email, class: "col-md-3 control-label" %>
                      <div class="col-md-9">
                          <%= f.email_field :email, class: "form-control"%>
                      </div>
                  </div>

                  <%= f.fields_for :profile_member do |profile_fields| %>
                    <div class="form-group">
                        <%= profile_fields.label :first_name, class: "col-md-3 control-label" %>
                        <div class="col-md-9">
                            <%= profile_fields.text_field :first_name, class: "form-control" %>
                        </div>
                    </div>

                    <div class="form-group">
                        <%= profile_fields.label :second_name, class: "col-md-3 control-label" %>
                        <div class="col-md-9">
                          <%= profile_fields.text_field :second_name, class: "form-control" %>
                        </div>
                    </div>
                  <% end %>

                  <div class="form-group">
                      <%= f.label :password, class: "col-md-3 control-label" %>
                      <div class="col-md-9">
                          <%= f.password_field :password, class: "form-control", autocomplete: "new-password" %>
                      </div>
                  </div>

                  <div class="form-group">
                      <%= f.label :password_confirmation, class: "col-md-3 control-label" %>
                      <div class="col-md-9">
                          <%= f.password_field :password_confirmation, class: "form-control", autocomplete: "new-password" %>
                      </div>
                  </div>

                  <div class="form-group">
                      <div class="col-md-offset-3 col-md-9">
                          <%= f.submit "Entrar", class: "btn btn-info" %>
                      </div>
                  </div>

              <% end %>
            </div>
        </div>
    </div>

</div>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>